import 'package:equatable/equatable.dart';

class Analysis extends Equatable {
  final String? actionsTaken;
  final double? activeProvisionalSum;
  final String? activeProvisionalSumPercentage;
  final double? actualCompletionRateforthisMonth;
  final double? actualPercentageofComplete;
  final String? additionalInformation;
  final String? agreementNumber;
  final String? agreementNumberForConsultancyServices;
  final String? agreementNumberForExecution;
  final double? agreementPeriod;
  final String? agreementSignDate;
  final String? agreementTotalAmount;
  final String? beneficiaryName;
  final String? budgetClausenumber;
  final String? budgetClauseNumber;
  final String? buildUpArea;
  final double? completedWorkAmount;
  final String? completedWorkAmountDate;
  final double? completedWorkandStoredMaterials;
  final String? completedWorkandStoredMaterialsPercentage;
  final String? completedWorkDuringthisMonth;
  final String? completionDateAfterExtension;
  final String? components;
  final String? consultancyServicesExpirationDate;
  final String? consultancyServicesStartDate;
  final String? consultantEmail;
  final String? consultantName;
  final String? consultantPhoneNumber;
  final String? consultantsId;
  final double? contractAmount;
  final String? contractorFax;
  final String? contractorName;
  final String? contractorPhoneNumber;
  final double? contractPeriod;
  final String? contractSigningDate;
  final String? contractualCompletionDate;
  final double? contractualCompletionPercentage;
  final String? countofActualDelay;
  final String? createdBy;
  final String? creationDate;
  final String? creationDatestr;
  final String? deputyManager;
  final String? deputyManagerEmail;
  final String? designAgreementValue;
  final String? designFinishDatewithExtension;
  final double? earlyStartCompletionrateforthisMonth;
  final double? elapsedTime;
  final double? estimatedFinancialProvision;
  final double? exchangePercentage;
  final String? expectedStartDate;
  final double? extensionPeriod;
  final String? financialProvision;
  final String? getPdfFile;
  final String? governorateName;
  final String? headofDepartment;
  final String? id;
  final String? idReplaced;
  final double? inactiveProvisionalSum;
  final String? inactiveProvisionalSumPercentage;
  final bool? isDeleted;
  final String? lastPaymentCertificateAmount;
  final String? lastPaymentCertificateDate;
  final double? lastPaymentNetAmount;
  final String? lastPaymentNetAmountDate;
  final double? lateStartCompletionRateforthisMonth;
  final String? latestPaymentCertificateNumber;
  final String? locationName;
  final double? measurementsVariations;
  final String? measurementsVariationsPercentage;
  final String? modificationDate;
  final String? modifiedBy;
  final String? month;
  final String? notes;
  final double? optionalWorksagreementAmount;
  final String? paymentCertificateNumber;
  final String? pdfFile;
  final String? pdfFileId;
  final String? percentageofElapsedTime;
  final String? periodDate;
  final String? periodTitle;
  final double? phase;
  final String? phaseName;
  final String? phoneNumberDeputyManager;
  final String? plannedHandoverDate;
  final String? plannedImplementationDate;
  final double? plannedPercentageofCompletion;
  final String? project;
  final String? projectEngineerEmail;
  final String? projectEngineerFax;
  final String? projectEngineerName;
  final String? projectEngineerPhoneNumber;
  final String? projectId;
  final String? projectName;
  final String? projectSector;
  final String? projectSectorId;
  final String? reasonsfortheDelay;
  final String? recoveryFinishDate;
  final double? recoveryPercentageofCompletion;
  final double? remainingDuration;
  final String? reportName;
  final String? siteArea;
  final String? startDate;
  final double? startStatus;
  final double? status;
  final String? statusStr;
  final double? sumOfProjectVariationOrders;
  final double? supervisionAgreementAmount;
  final double? theEstimatedValueofTheProject;
  final double? theValueoftheExecutionContractWithoutProtectionWorks;
  final double? totalContractAmountAfterExtension;
  final double? totalPaidAmount;
  final String? totalValueofOutgoingPaymentsFinancialforDepartment;
  final double? totalValueofOutgoingPaymentsforSector;
  final double? totalVariationOrders;
  final String? variationOrders;
  final String? variationOrdersId;
  final String? variationOrdersPercentage;
  final List<String>? variationOrdersValues;
  final String? year;

  Analysis({
    this.actionsTaken = "",
    this.activeProvisionalSum = 0.0,
    this.activeProvisionalSumPercentage = "",
    this.actualCompletionRateforthisMonth = 0.0,
    this.actualPercentageofComplete = 0,
    this.additionalInformation = "",
    this.agreementNumber = "",
    this.agreementNumberForConsultancyServices = "",
    this.agreementNumberForExecution = "",
    this.agreementPeriod = 0,
    this.agreementSignDate = "",
    this.agreementTotalAmount = "",
    this.beneficiaryName = "",
    this.budgetClausenumber = "",
    this.budgetClauseNumber = "",
    this.buildUpArea = "",
    this.completedWorkAmount = 0.0,
    this.completedWorkAmountDate = "",
    this.completedWorkandStoredMaterials = 0.0,
    this.completedWorkandStoredMaterialsPercentage = "",
    this.completedWorkDuringthisMonth = "",
    this.completionDateAfterExtension = "",
    this.components = "",
    this.consultancyServicesExpirationDate = "",
    this.consultancyServicesStartDate = "",
    this.consultantEmail = "",
    this.consultantName = "",
    this.consultantPhoneNumber = "",
    this.consultantsId = "",
    this.contractAmount = 0.0,
    this.contractorFax = "",
    this.contractorName = "",
    this.contractorPhoneNumber = "",
    this.contractPeriod = 0,
    this.contractSigningDate = "",
    this.contractualCompletionDate = "",
    this.contractualCompletionPercentage = 0.0,
    this.countofActualDelay = "",
    this.createdBy = "",
    this.creationDate = "",
    this.creationDatestr = "",
    this.deputyManager = "",
    this.deputyManagerEmail = "",
    this.designAgreementValue = "",
    this.designFinishDatewithExtension = "",
    this.earlyStartCompletionrateforthisMonth = 0,
    this.elapsedTime = 0,
    this.estimatedFinancialProvision = 0,
    this.exchangePercentage = 0,
    this.expectedStartDate = "",
    this.extensionPeriod = 0,
    this.financialProvision = "",
    this.getPdfFile = "",
    this.governorateName = "",
    this.headofDepartment = "",
    this.id = "",
    this.idReplaced = "",
    this.inactiveProvisionalSum = 0,
    this.inactiveProvisionalSumPercentage = "",
    this.isDeleted = false,
    this.lastPaymentCertificateAmount = "",
    this.lastPaymentCertificateDate = "",
    this.lastPaymentNetAmount = 0.0,
    this.lastPaymentNetAmountDate = "",
    this.lateStartCompletionRateforthisMonth = 0,
    this.latestPaymentCertificateNumber = "",
    this.locationName = "",
    this.measurementsVariations = 0,
    this.measurementsVariationsPercentage = "",
    this.modificationDate = "",
    this.modifiedBy = "",
    this.month = "",
    this.notes = "",
    this.optionalWorksagreementAmount = 0,
    this.paymentCertificateNumber = "",
    this.pdfFile = "",
    this.pdfFileId = "",
    this.percentageofElapsedTime = "",
    this.periodDate = "",
    this.periodTitle = "",
    this.phase = 0,
    this.phaseName = "",
    this.phoneNumberDeputyManager = "",
    this.plannedHandoverDate = "",
    this.plannedImplementationDate = "",
    this.plannedPercentageofCompletion = 0,
    this.project = "",
    this.projectEngineerEmail = "",
    this.projectEngineerFax = "",
    this.projectEngineerName = "",
    this.projectEngineerPhoneNumber = "",
    this.projectId = "",
    this.projectName = "",
    this.projectSector = "",
    this.projectSectorId = "",
    this.reasonsfortheDelay = "",
    this.recoveryFinishDate = "",
    this.recoveryPercentageofCompletion = 0,
    this.remainingDuration = 0,
    this.reportName = "",
    this.siteArea = "",
    this.startDate = "",
    this.startStatus = 0,
    this.status = 0,
    this.statusStr = "",
    this.sumOfProjectVariationOrders = 0,
    this.supervisionAgreementAmount = 0,
    this.theEstimatedValueofTheProject = 0,
    this.theValueoftheExecutionContractWithoutProtectionWorks = 0.0,
    this.totalContractAmountAfterExtension = 0,
    this.totalPaidAmount = 0.0,
    this.totalValueofOutgoingPaymentsFinancialforDepartment = "",
    this.totalValueofOutgoingPaymentsforSector = 0.0,
    this.totalVariationOrders = 0,
    this.variationOrders = "",
    this.variationOrdersId = "",
    this.variationOrdersPercentage = "",
    this.variationOrdersValues = const [],
    this.year = "",
  });

  @override
  List<Object?> get props => [identityHashCode(this)];
}
